In [9]:
#Q1-a
import pandas as pd                                                         
































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

transactions=[['bread','milk'],
              ['bread','diaper','beer','eggs'],
              ['milk','diaper','beer','coke'],
              ['bread','milk','diaper','beer'],
              ['bread','milk','diaper','coke']]

te=TransactionEncoder()
te_array=te.fit(transactions).transform(transactions)
df=pd.DataFrame(te_array,columns=te.columns_)
print(df)

#for min_support 0.5
print("\nFor min_support 0.5\n")
freq_items=apriori(df,min_support=0.5,use_colnames=True)
print(freq_items)
rules=association_rules(freq_items,metric='support',min_threshold=0.05)
rules=rules.sort_values(['support','confidence'],ascending=[False,False])
rules

    beer  bread   coke  diaper   eggs   milk
0  False   True  False   False  False   True
1   True   True  False    True   True  False
2   True  False   True    True  False   True
3   True   True  False    True  False   True
4  False   True   True    True  False   True

For min_support 0.5

   support                    itemsets
0      0.6           frozenset({beer})
1      0.8          frozenset({bread})
2      0.8         frozenset({diaper})
3      0.8           frozenset({milk})
4      0.6   frozenset({beer, diaper})
5      0.6  frozenset({diaper, bread})
6      0.6    frozenset({bread, milk})
7      0.6   frozenset({diaper, milk})

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({beer}),frozenset({diaper}),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
1,frozenset({diaper}),frozenset({beer}),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875
2,frozenset({diaper}),frozenset({bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
3,frozenset({bread}),frozenset({diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
4,frozenset({bread}),frozenset({milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
5,frozenset({milk}),frozenset({bread}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
6,frozenset({diaper}),frozenset({milk}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
7,frozenset({milk}),frozenset({diaper}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750

In [2]:
#q1-b
#for min_support 0.3
print("\nFor min_support 0.3\n")

freq_items=apriori(df,min_support=0.3,use_colnames=True)
print(freq_items)
rules=association_rules(freq_items,metric='support',min_threshold=0.05)
rules=rules.sort_values(['support','confidence'],ascending=[False,False])
rules

For min_support 0.3

    support                          itemsets
0       0.6                 frozenset({beer})
1       0.8                frozenset({bread})
2       0.4                 frozenset({coke})
3       0.8               frozenset({diaper})
4       0.8                 frozenset({milk})
5       0.4          frozenset({beer, bread})
6       0.6         frozenset({beer, diaper})
7       0.4           frozenset({beer, milk})
8       0.6        frozenset({diaper, bread})
9       0.6          frozenset({bread, milk})
10      0.4         frozenset({coke, diaper})
11      0.4           frozenset({coke, milk})
12      0.6         frozenset({diaper, milk})
13      0.4  frozenset({beer, diaper, bread})
14      0.4   frozenset({beer, diaper, milk})
15      0.4  frozenset({diaper, bread, milk})
16      0.4   frozenset({coke, diaper, milk})

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
2,frozenset({beer}),frozenset({diaper}),0.6,0.8,0.6,1.000000,1.250000,1.0,0.12,inf,0.500000,0.750000,1.000000,0.875000
3,frozenset({diaper}),frozenset({beer}),0.8,0.6,0.6,0.750000,1.250000,1.0,0.12,1.6,1.000000,0.750000,0.375000,0.875000
6,frozenset({diaper}),frozenset({bread}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
7,frozenset({bread}),frozenset({diaper}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
8,frozenset({bread}),frozenset({milk}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
9,frozenset({milk}),frozenset({bread}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
14,frozenset({diaper}),frozenset({milk}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
15,frozenset({milk}),frozenset({diaper}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
10,frozenset({coke}),frozenset({diaper}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
12,frozenset({coke}),frozenset({milk}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
17,"frozenset({beer, bread})",frozenset({diaper}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
23,"frozenset({beer, milk})",frozenset({diaper}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
34,"frozenset({coke, diaper})",frozenset({milk}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
35,"frozenset({coke, milk})",frozenset({diaper}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
37,frozenset({coke}),"frozenset({diaper, milk})",0.4,0.6,0.4,1.000000,1.666667,1.0,0.16,inf,0.666667,0.666667,1.000000,0.833333
0,frozenset({beer}),frozenset({bread}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
4,frozenset({beer}),frozenset({milk}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
16,"frozenset({beer, diaper})",frozenset({bread}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
18,"frozenset({diaper, bread})",frozenset({beer}),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250000,0.500000,0.166667,0.666667
19,frozenset({beer}),"frozenset({diaper, bread})",0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250000,0.500000,0.166667,0.666667
22,"frozenset({beer, diaper})",frozenset({milk}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
24,"frozenset({diaper, milk})",frozenset({beer}),0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250000,0.500000,0.166667,0.666667
25,frozenset({beer}),"frozenset({diaper, milk})",0.6,0.6,0.4,0.666667,1.111111,1.0,0.04,1.2,0.250000,0.500000,0.166667,0.666667
28,"frozenset({diaper, bread})",frozenset({milk}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
29,"frozenset({diaper, milk})",frozenset({bread}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
30,"frozenset({bread, milk})",frozenset({diaper}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
36,"frozenset({diaper, milk})",frozenset({coke}),0.6,0.4,0.4,0.666667,1.666667,1.0,0.16,1.8,1.000000,0.666667,0.444444,0.833333
1,frozenset({bread}),frozenset({beer}),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
5,frozenset({milk}),frozenset({beer}),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
11,frozenset({diaper}),frozenset({coke}),0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
13,frozenset({milk}),frozenset({coke}),0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
20,frozenset({diaper}),"frozenset({beer, bread})",0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
21,frozenset({bread}),"frozenset({beer, diaper})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
26,frozenset({diaper}),"frozenset({beer, milk})",0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
27,frozenset({milk}),"frozenset({beer, diaper})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
31,frozenset({diaper}),"frozenset({bread, milk})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
32,frozenset({bread}),"frozenset({diaper, milk})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
33,frozenset({milk}),"frozenset({diaper, bread})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
38,frozenset({diaper}),"frozenset({coke, milk})",0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
39,frozenset({milk}),"frozenset({coke, diaper})",0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000

In [3]:
#for min_support 0.7
print("\nFor min_support 0.7\n")

freq_items=apriori(df,min_support=0.7,use_colnames=True)
print(freq_items)
rules=association_rules(freq_items,metric='support',min_threshold=0.05)
rules=rules.sort_values(['support','confidence'],ascending=[False,False])
rules

For min_support 0.7

   support             itemsets
0      0.8   frozenset({bread})
1      0.8  frozenset({diaper})
2      0.8    frozenset({milk})

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [5]:
#Q2
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

transactions=[['pen','pencil','eraser'],
              ['pen','notebook','eraser','sharpener'],
              ['pencil','eraser','sharpener'],
              ['pen','pencil','sharpener'],
              ['pen','pencil','notebook','eraser']]

te=TransactionEncoder()
te_array=te.fit(transactions).transform(transactions)
df=pd.DataFrame(te_array,columns=te.columns_)
print(df)

#for min_support 0.5
print("\nFor min_support 0.5\n")
freq_items=apriori(df,min_support=0.5,use_colnames=True)
print(freq_items)
rules=association_rules(freq_items,metric='support',min_threshold=0.05)
rules=rules.sort_values(['support','confidence'],ascending=[False,False])
rules

   eraser  notebook    pen  pencil  sharpener
0    True     False   True    True      False
1    True      True   True   False       True
2    True     False  False    True       True
3   False     False   True    True       True
4    True      True   True    True      False

For min_support 0.5

   support                     itemsets
0      0.8          frozenset({eraser})
1      0.8             frozenset({pen})
2      0.8          frozenset({pencil})
3      0.6       frozenset({sharpener})
4      0.6     frozenset({eraser, pen})
5      0.6  frozenset({pencil, eraser})
6      0.6     frozenset({pencil, pen})

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({eraser}),frozenset({pen}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75
1,frozenset({pen}),frozenset({eraser}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75
2,frozenset({pencil}),frozenset({eraser}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75
3,frozenset({eraser}),frozenset({pencil}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75
4,frozenset({pencil}),frozenset({pen}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75
5,frozenset({pen}),frozenset({pencil}),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.6,-0.25,0.75

In [6]:
#for min_support 0.7
print("\nFor min_support 0.7\n")
freq_items=apriori(df,min_support=0.7,use_colnames=True)
print(freq_items)
rules=association_rules(freq_items,metric='support',min_threshold=0.05)
rules=rules.sort_values(['support','confidence'],ascending=[False,False])
rules

For min_support 0.7

   support             itemsets
0      0.8  frozenset({eraser})
1      0.8     frozenset({pen})
2      0.8  frozenset({pencil})

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [7]:
#for min_support 0.3
print("\nFor min_support 0.3\n")
freq_items=apriori(df,min_support=0.3,use_colnames=True)
print(freq_items)
rules=association_rules(freq_items,metric='support',min_threshold=0.05)
rules=rules.sort_values(['support','confidence'],ascending=[False,False])
rules

For min_support 0.3

    support                            itemsets
0       0.8                 frozenset({eraser})
1       0.4               frozenset({notebook})
2       0.8                    frozenset({pen})
3       0.8                 frozenset({pencil})
4       0.6              frozenset({sharpener})
5       0.4       frozenset({notebook, eraser})
6       0.6            frozenset({eraser, pen})
7       0.6         frozenset({pencil, eraser})
8       0.4      frozenset({eraser, sharpener})
9       0.4          frozenset({notebook, pen})
10      0.6            frozenset({pencil, pen})
11      0.4         frozenset({pen, sharpener})
12      0.4      frozenset({pencil, sharpener})
13      0.4  frozenset({notebook, eraser, pen})
14      0.4    frozenset({pencil, eraser, pen})

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
2,frozenset({eraser}),frozenset({pen}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
3,frozenset({pen}),frozenset({eraser}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
4,frozenset({pencil}),frozenset({eraser}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
5,frozenset({eraser}),frozenset({pencil}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
10,frozenset({pencil}),frozenset({pen}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
11,frozenset({pen}),frozenset({pencil}),0.8,0.8,0.6,0.750000,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250000,0.750000
0,frozenset({notebook}),frozenset({eraser}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
8,frozenset({notebook}),frozenset({pen}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
16,"frozenset({notebook, eraser})",frozenset({pen}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
17,"frozenset({notebook, pen})",frozenset({eraser}),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
19,frozenset({notebook}),"frozenset({eraser, pen})",0.4,0.6,0.4,1.000000,1.666667,1.0,0.16,inf,0.666667,0.666667,1.000000,0.833333
7,frozenset({sharpener}),frozenset({eraser}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
13,frozenset({sharpener}),frozenset({pen}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
15,frozenset({sharpener}),frozenset({pencil}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
18,"frozenset({eraser, pen})",frozenset({notebook}),0.6,0.4,0.4,0.666667,1.666667,1.0,0.16,1.8,1.000000,0.666667,0.444444,0.833333
22,"frozenset({pencil, eraser})",frozenset({pen}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
23,"frozenset({pencil, pen})",frozenset({eraser}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
24,"frozenset({eraser, pen})",frozenset({pencil}),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
1,frozenset({eraser}),frozenset({notebook}),0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
6,frozenset({eraser}),frozenset({sharpener}),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
9,frozenset({pen}),frozenset({notebook}),0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
12,frozenset({pen}),frozenset({sharpener}),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
14,frozenset({pencil}),frozenset({sharpener}),0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
20,frozenset({eraser}),"frozenset({notebook, pen})",0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
21,frozenset({pen}),"frozenset({notebook, eraser})",0.8,0.4,0.4,0.500000,1.250000,1.0,0.08,1.2,1.000000,0.500000,0.166667,0.750000
25,frozenset({pencil}),"frozenset({eraser, pen})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
26,frozenset({eraser}),"frozenset({pencil, pen})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333
27,frozenset({pen}),"frozenset({pencil, eraser})",0.8,0.6,0.4,0.500000,0.833333,1.0,-0.08,0.8,-0.500000,0.400000,-0.250000,0.583333